### ISSUE TITLE
HTTP错误：429 too many requests

### ISSUE THREAD

**Issue by mccleaner** [YidaozhanYa/NSEmuHelper#10]
检查更新和下载的时候都会出现，一开始以为是one drive或者代理引起的，但是在尝试多种链接方式后依然出现该错误。

**Comment by mccleaner** [comment]
关掉应用内github api代理就可以了。

**Comment by YidaozhanYa** [comment]
https://tieba.baidu.com/p/7956433277

**Comment by YidaozhanYa** [comment]
请不要关闭这个 issue，直到攻击停止为止。

**Comment by YidaozhanYa** [comment]
暂时的解决办法：在模拟器助手内关掉「始终代理 GitHub API」，打开「跳过固件 MD5 校验」。
