### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by JoeyChoGG** [YidaozhanYa/NSEmuHelper#11]
系统win11，软件2.02版本
1.软件更新会弹出错误，提示更换源，更换后问题依旧；
2.导入模拟器后固件版本检测为未知；
3.更新模拟器会弹出错误，提示更换源，更换后问题依旧，一部分源提示错误，另一部分直接导致闪退

**Comment by LinFangxin** [comment]
同样问题，目前只有更新模拟器偶尔可以，更新固件和其他会报错

**Comment by zkyhzxf** [comment]
同样问题，直接卡死，没法用
![image](https://user-images.githubusercontent.com/35629617/189787548-2d23a32d-f394-401d-9cc1-c1430c3831d5.png)

**Comment by YidaozhanYa** [comment]
在 8 月 2 号的时候，被打光了所有流量，停止维护了
