### ISSUE TITLE
最新的1.0.4总是卡死

### ISSUE THREAD

**Issue by King-Nameless** [YidaozhanYa/NSEmuHelper#4]
![QQ图片20220208080921](https://user-images.githubusercontent.com/83447487/152893288-d1ee7d9a-39e8-47ae-a55d-95850f5fdc95.png)
![QQ图片20220208080612](https://user-images.githubusercontent.com/83447487/152893325-2dad9f5b-af53-465f-90c7-d1da5f3d634b.png)
yuzu的没试，ryujinx用的就是你的中文版，固件版本选择后没问题，模拟器版本号修改了也没问题，但只要模拟器版本换一个选项就立马卡死
新建路径可以下载最新版本模拟器，使用没什么问题，但在相关设置里也是同样的问题，换版本就卡死
另一点就是，明明2个模拟器共4个版本，但只有2个路径设置，若是要换的话，次次都要重新设置路径，很不方便，即便将来会合并，也不知道要多久呢，最起码ryujinx光是主线版本都有个v的支线，ldn更是好久才会更新一次

**Comment by King-Nameless** [comment]
![{KOENAVB22}X03R}GON@A6B](https://user-images.githubusercontent.com/83447487/152901497-f94b87c9-e30a-42a1-a76b-bdc7bf943c9f.png)
下了你的中文版，解压后publish文件夹改成RyujiNX，然后NSEmuHelper设置路径，选择完固件就这样提示error70，之后重新打开直接识别为主线版，在相关设置里，选中文版和联机版都识别成联机版，主线版识别为主线版，另外不管选哪个，都提示error70

![image](https://user-images.githubusercontent.com/83447487/152903102-715e322e-340e-4597-993c-030e46a0c1de.png)
数据文件转移也用不了，也会提示error70

**Comment by King-Nameless** [comment]
![image](https://user-images.githubusercontent.com/83447487/152904137-c947ef84-96af-4e71-9254-b4421f70f66b.png)
现在直接用NSEmuHelper安装，安装完成后，进去识别为中文版，没问题，然后相关设置里就默认为主线版了
![image](https://user-images.githubusercontent.com/83447487/152904293-b07d63be-63e6-437e-8541-bd0ac52f1899.png)
换成中文版，他后面的版本号又变成了ldn联机版……
![9{K(F}N LADYE4F0(I1T65O](https://user-images.githubusercontent.com/83447487/152904605-3717cd83-7852-407b-b92e-eb171561e644.png)
我强行改版本号，数据是提示转移成功了，但……
![image](https://user-images.githubusercontent.com/83447487/152904665-ff39d411-72eb-4810-abee-b99223901e0d.png)

这也就算了，显示不正确不管他，但我把c盘存档mod之类的拷贝进去，原来的存档路径portable文件夹没有消失不说，甚至还会同步改变？而游戏上右键打开的文件夹仍然指向portable文件夹
![image](https://user-images.githubusercontent.com/83447487/152907379-a6ed7aba-eb37-47c9-aebd-b061da1f3c24.png)



这bug实在太多了，就想给c盘瘦瘦身的，结果搞了半天，还不如就用你的中文版，解压完直接用算了_(:зゝ∠)_

**Comment by YidaozhanYa** [comment]
1. 卡死的问题是因为网络，既然你能使用Github，何不使用Github下载源呢
2. rt76可能是因为你工具安装路径过于复杂导致
3. 一般人应该不会同时装Yuzu的ea和主线，ryujinx的英文和中文吧

**Comment by King-Nameless** [comment]
> 1. 卡死的问题是因为网络，既然你能使用Github，何不使用Github下载源呢
> 2. rt76可能是因为你工具安装路径过于复杂导致
> 3. 一般人应该不会同时装Yuzu的ea和主线，ryujinx的英文和中文吧

github有时候正常有时候下载又很慢
路径应该不至于复杂吧，毕竟就3层文件夹，而且一般来说全英文路径基本不会出问题才对
yuzu确实一般就用一个，但ruyjinx现在会用主线/中文、ldn联机版这2个

**Comment by YidaozhanYa** [comment]
联机版可以单独安装，并且主线和联机不建议使用同一个数据文件夹
