### ISSUE TITLE
可以使用uno、Avalonia和CPF(cpf是国人开发的基于.net core的跨平台ui框架win mac和liunx)

### ISSUE THREAD

**Issue by wuliangtdi** [YidaozhanYa/NSEmuHelper#7]
这三款都可以去看看 
cpf地址: http://cpf.cskin.net/
Avalonia地址: https://github.com/AvaloniaUI/Avalonia
uno地址: https://github.com/unoplatform/uno

**Comment by YidaozhanYa** [comment]
我不使用 Windows，并且虚拟机带不动 Visual Studio。

这个 issue 先开着，以后考虑。

**Comment by YidaozhanYa** [comment]
基于 VB.NET WinForm 重构完成，可以关掉了～
