### ISSUE TITLE
在非Unicode环境（如日语）下运行软件会乱码

### ISSUE THREAD

**Issue by Chillalalal-kira** [YidaozhanYa/NSEmuHelper#8]
![1](https://user-images.githubusercontent.com/29849577/165915612-ed330c9a-ef7c-4765-bbdc-33fb6423f1c4.jpg)
![2](https://user-images.githubusercontent.com/29849577/165915709-a059b902-f5ad-43fd-8a01-2d0c74ae183b.jpg)

**Comment by YidaozhanYa** [comment]
这是 Visual Basic 6 自身的问题，无解。

可以尝试使用 Locale Emulator 之类的跨区软件。
